-- Prospects pipeline (Phase 0 — Stream A)
-- Adds two tables (prospects, prospect_outreach), RLS policies, set_updated_at trigger.

create table if not exists public.prospects (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone not null default now(),
    source text not null,
    source_id text,
    source_url text,
    source_payload jsonb,
    company_name text not null,
    sector text,
    website text,
    phone text,
    email text,
    address text,
    zipcode text,
    city text,
    country text,
    linkedin_url text,
    decision_maker_name text,
    decision_maker_title text,
    decision_maker_linkedin_url text,
    decision_maker_email text,
    decision_maker_email_status text,
    status text not null default 'new',
    qualification_score smallint,
    rejection_reason text,
    last_touched_at timestamp with time zone,
    next_action_at timestamp with time zone,
    company_id bigint references public.companies(id) on delete set null,
    contact_id bigint references public.contacts(id) on delete set null,
    promoted_at timestamp with time zone,
    sales_id bigint references public.sales(id) on delete set null,
    tags text[]
);

create index if not exists idx_prospects_status on public.prospects(status);
create index if not exists idx_prospects_company_id on public.prospects(company_id);
create unique index if not exists uq_prospects_source on public.prospects(source, source_id) where source_id is not null;

create table if not exists public.prospect_outreach (
    id bigint generated by default as identity primary key,
    prospect_id bigint not null references public.prospects(id) on delete cascade,
    occurred_at timestamp with time zone not null default now(),
    channel text not null,
    direction text not null,
    subject text,
    body text,
    metadata jsonb,
    sales_id bigint references public.sales(id) on delete set null
);

create index if not exists idx_outreach_prospect on public.prospect_outreach(prospect_id, occurred_at desc);

CREATE OR REPLACE FUNCTION "public"."set_updated_at"() RETURNS "trigger"
    LANGUAGE "plpgsql"
    SET "search_path" TO 'public'
    AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$;

create or replace trigger prospects_set_updated_at
    before update on public.prospects
    for each row execute function public.set_updated_at();

alter table public.prospects enable row level security;
create policy "Enable read access for authenticated users" on public.prospects for select to authenticated using (true);
create policy "Enable insert for authenticated users only" on public.prospects for insert to authenticated with check (true);
create policy "Enable update for authenticated users only" on public.prospects for update to authenticated using (true) with check (true);
create policy "Prospects Delete Policy" on public.prospects for delete to authenticated using (true);

alter table public.prospect_outreach enable row level security;
create policy "Enable read access for authenticated users" on public.prospect_outreach for select to authenticated using (true);
create policy "Enable insert for authenticated users only" on public.prospect_outreach for insert to authenticated with check (true);
create policy "Enable update for authenticated users only" on public.prospect_outreach for update to authenticated using (true) with check (true);
create policy "Outreach Delete Policy" on public.prospect_outreach for delete to authenticated using (true);
