-- Allo (withallo.com) phone integration: per-user mapping between CRM contacts
-- and Allo "contact" records. One Allo account is shared across CRM users, so
-- the mapping is keyed by user_id to allow each user to scope their sync.

CREATE TABLE public.allo_contact_mappings (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  contact_id bigint NOT NULL REFERENCES public.contacts(id) ON DELETE CASCADE,
  allo_contact_id text NOT NULL,
  last_synced_at timestamptz NOT NULL DEFAULT now(),
  created_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE(user_id, contact_id),
  UNIQUE(user_id, allo_contact_id)
);

CREATE INDEX idx_allo_contact_mappings_user ON public.allo_contact_mappings(user_id);
CREATE INDEX idx_allo_contact_mappings_contact ON public.allo_contact_mappings(contact_id);

ALTER TABLE public.allo_contact_mappings ENABLE ROW LEVEL SECURITY;

-- Users can read their own mappings; writes are done by edge functions
-- (service_role) which bypass RLS.
CREATE POLICY "users_read_own_allo_mappings" ON public.allo_contact_mappings
  FOR SELECT USING (user_id = auth.uid());

CREATE POLICY "service_role_full_access" ON public.allo_contact_mappings
  FOR ALL USING (auth.role() = 'service_role');
