-- Allo ↔ Nosho-CRM sync — Phase 1 (calls only).
--
-- Foundations for the Allo integration:
--   • call_logs       — one row per Allo call.completed event
--   • sms_messages    — created now so phase 2 can land without another migration
--   • allo_contact_links — pivot CRM contact ↔ Allo contact id
--   • allo_line_owners   — Allo phone number → sales_id mapping
--   • contacts._sync_origin — anti-loop marker for the (future) reverse sync
--   • lead-from-allo tag    — applied to contacts auto-created by the webhook
--   • process_allo_call(jsonb) — idempotent matcher+writer used by n8n
--
-- All writes go through process_allo_call() so the webhook stays a thin
-- transport: validate signature in n8n, then forward the payload to Postgres.

--
-- 1. Marker column on contacts (used by phase 3 to break feedback loops).
--
alter table public.contacts
  add column if not exists _sync_origin text;

comment on column public.contacts._sync_origin is
  'Identifier of the system that last wrote this row via an external sync (e.g. ''allo''). NULL = local CRM edit. Used by reverse-sync workflows to skip echoes.';

--
-- 2. Allo line ↔ sales mapping (seeded manually after migration runs).
--
create table if not exists public.allo_line_owners (
    id bigint generated by default as identity primary key,
    allo_phone_number text not null unique,
    sales_id bigint not null references public.sales(id) on delete cascade,
    label text,
    created_at timestamp with time zone not null default now()
);

create index if not exists idx_allo_line_owners_sales on public.allo_line_owners(sales_id);

--
-- 3. Pivot mapping CRM contact ↔ Allo contact id.
--    Composite PK so the same CRM contact can be linked to multiple Allo
--    contact records over time (rare, but cheaper than a one-to-one).
--
create table if not exists public.allo_contact_links (
    contact_id bigint not null references public.contacts(id) on delete cascade,
    allo_contact_id text not null,
    created_at timestamp with time zone not null default now(),
    primary key (contact_id, allo_contact_id)
);

create unique index if not exists uq_allo_contact_links_allo_id
    on public.allo_contact_links(allo_contact_id);

--
-- 4. Call logs.
--
create table if not exists public.call_logs (
    id bigint generated by default as identity primary key,
    allo_call_id text not null unique,
    direction text not null check (direction in ('inbound', 'outbound')),
    from_number text,
    to_number text,
    line_phone text,
    status text,
    duration_seconds integer,
    started_at timestamp with time zone,
    ended_at timestamp with time zone,
    recording_url text,
    ai_summary text,
    transcript text,
    contact_id bigint references public.contacts(id) on delete set null,
    sales_id bigint references public.sales(id) on delete set null,
    deal_id bigint references public.deals(id) on delete set null,
    raw_payload jsonb not null,
    created_at timestamp with time zone not null default now()
);

create index if not exists idx_call_logs_contact on public.call_logs(contact_id, started_at desc);
create index if not exists idx_call_logs_sales on public.call_logs(sales_id, started_at desc);
create index if not exists idx_call_logs_deal on public.call_logs(deal_id, started_at desc);
create index if not exists idx_call_logs_started_at on public.call_logs(started_at desc);

--
-- 5. SMS messages (table only — phase 2 will add process_allo_sms()).
--
create table if not exists public.sms_messages (
    id bigint generated by default as identity primary key,
    allo_message_id text not null unique,
    direction text not null check (direction in ('inbound', 'outbound')),
    from_number text,
    to_number text,
    line_phone text,
    body text,
    sent_at timestamp with time zone,
    contact_id bigint references public.contacts(id) on delete set null,
    sales_id bigint references public.sales(id) on delete set null,
    raw_payload jsonb not null,
    created_at timestamp with time zone not null default now()
);

create index if not exists idx_sms_messages_contact on public.sms_messages(contact_id, sent_at desc);
create index if not exists idx_sms_messages_sales on public.sms_messages(sales_id, sent_at desc);

--
-- 6. Tag for contacts auto-created by the webhook.
--
insert into public.tags (name, color)
select 'lead-from-allo', '#99c1de'
where not exists (select 1 from public.tags where name = 'lead-from-allo');

--
-- 7. RLS policies — same pattern as the rest of the CRM (authenticated full access).
--
alter table public.allo_line_owners enable row level security;
create policy "Enable read access for authenticated users" on public.allo_line_owners for select to authenticated using (true);
create policy "Enable insert for authenticated users only" on public.allo_line_owners for insert to authenticated with check (true);
create policy "Enable update for authenticated users only" on public.allo_line_owners for update to authenticated using (true) with check (true);
create policy "Allo Line Owners Delete Policy" on public.allo_line_owners for delete to authenticated using (true);

alter table public.allo_contact_links enable row level security;
create policy "Enable read access for authenticated users" on public.allo_contact_links for select to authenticated using (true);
create policy "Enable insert for authenticated users only" on public.allo_contact_links for insert to authenticated with check (true);
create policy "Enable update for authenticated users only" on public.allo_contact_links for update to authenticated using (true) with check (true);
create policy "Allo Contact Links Delete Policy" on public.allo_contact_links for delete to authenticated using (true);

alter table public.call_logs enable row level security;
create policy "Enable read access for authenticated users" on public.call_logs for select to authenticated using (true);
create policy "Enable insert for authenticated users only" on public.call_logs for insert to authenticated with check (true);
create policy "Enable update for authenticated users only" on public.call_logs for update to authenticated using (true) with check (true);
create policy "Call Logs Delete Policy" on public.call_logs for delete to authenticated using (true);

alter table public.sms_messages enable row level security;
create policy "Enable read access for authenticated users" on public.sms_messages for select to authenticated using (true);
create policy "Enable insert for authenticated users only" on public.sms_messages for insert to authenticated with check (true);
create policy "Enable update for authenticated users only" on public.sms_messages for update to authenticated using (true) with check (true);
create policy "SMS Messages Delete Policy" on public.sms_messages for delete to authenticated using (true);

--
-- 8. Grants.
--
grant all on table public.allo_line_owners to authenticated;
grant all on table public.allo_line_owners to service_role;
grant all on table public.allo_contact_links to authenticated;
grant all on table public.allo_contact_links to service_role;
grant all on table public.call_logs to authenticated;
grant all on table public.call_logs to service_role;
grant all on table public.sms_messages to authenticated;
grant all on table public.sms_messages to service_role;

--
-- 9. Helpers.
--

-- Normalize a phone number for matching: keep digits only, then return the
-- last 9 digits (covers FR mobiles whether stored as +33XXXXXXXXX, 0XXXXXXXXX,
-- or 33XXXXXXXXX). Returns NULL when input is too short or null.
create or replace function public.allo_normalize_phone(p text)
returns text
language sql
immutable
set search_path to ''
as $$
  select case
    when p is null then null
    when length(regexp_replace(p, '\D', '', 'g')) < 9 then null
    else right(regexp_replace(p, '\D', '', 'g'), 9)
  end
$$;

grant all on function public.allo_normalize_phone(text) to authenticated;
grant all on function public.allo_normalize_phone(text) to service_role;

--
-- 10. process_allo_call(payload jsonb) → jsonb
--
-- Atomic matcher + writer for an Allo `call.completed` event.
-- Idempotent on `allo_call_id`: replaying the same payload returns the
-- existing call_logs row without creating duplicates.
--
-- Expected payload shape (lenient — extra fields are kept in raw_payload):
--   {
--     "event": "call.completed",
--     "data": {
--       "call_id":          "<unique allo id>",
--       "direction":        "inbound" | "outbound",
--       "from":             "+33...",
--       "to":               "+33...",
--       "line_phone":       "+33...",       -- optional, falls back to from/to
--       "started_at":       "ISO 8601",
--       "ended_at":         "ISO 8601",
--       "duration_seconds": 120,
--       "status":           "answered" | "missed" | ...,
--       "recording_url":    "https://...",
--       "ai_summary":       "...",
--       "transcript":       "...",
--       "contact_id":       "<allo contact id>"  -- optional
--     }
--   }
--
create or replace function public.process_allo_call(p_payload jsonb)
returns jsonb
language plpgsql
security definer
set search_path to ''
as $$
declare
  v_data            jsonb := coalesce(p_payload -> 'data', p_payload);
  v_call_id         text  := v_data ->> 'call_id';
  v_direction       text  := lower(coalesce(v_data ->> 'direction', 'inbound'));
  v_from            text  := v_data ->> 'from';
  v_to              text  := v_data ->> 'to';
  v_line_phone      text  := v_data ->> 'line_phone';
  v_allo_contact_id text  := v_data ->> 'contact_id';
  v_external_phone  text;
  v_external_norm   text;
  v_sales_id        bigint;
  v_contact_id      bigint;
  v_deal_id         bigint;
  v_lead_tag_id     bigint;
  v_existing        public.call_logs%rowtype;
  v_inserted_id     bigint;
  v_was_inserted    boolean := false;
  v_contact_created boolean := false;
begin
  if v_call_id is null or v_call_id = '' then
    raise exception 'process_allo_call: payload missing data.call_id';
  end if;

  -- Fast path: idempotent re-delivery. Return the existing row untouched.
  select * into v_existing from public.call_logs where allo_call_id = v_call_id;
  if found then
    return jsonb_build_object(
      'call_log_id',  v_existing.id,
      'contact_id',   v_existing.contact_id,
      'sales_id',     v_existing.sales_id,
      'deal_id',      v_existing.deal_id,
      'inserted',     false,
      'contact_created', false
    );
  end if;

  -- Resolve which Allo line was used. Falls back to the local side of the
  -- call when line_phone is not supplied (outbound: from = line; inbound: to = line).
  if v_line_phone is null or v_line_phone = '' then
    v_line_phone := case when v_direction = 'outbound' then v_from else v_to end;
  end if;

  -- Map line → sales_id via allo_line_owners (left join on normalized form).
  select lo.sales_id into v_sales_id
    from public.allo_line_owners lo
   where public.allo_normalize_phone(lo.allo_phone_number)
       = public.allo_normalize_phone(v_line_phone)
   limit 1;

  -- The "external" phone is the counterparty (the contact's number).
  v_external_phone := case when v_direction = 'outbound' then v_to else v_from end;
  v_external_norm  := public.allo_normalize_phone(v_external_phone);

  -- Try to match an existing CRM contact:
  --   a) via the pivot if Allo gave us a contact id we've seen before
  --   b) otherwise by phone number, normalized
  if v_allo_contact_id is not null and v_allo_contact_id <> '' then
    select acl.contact_id into v_contact_id
      from public.allo_contact_links acl
     where acl.allo_contact_id = v_allo_contact_id
     limit 1;
  end if;

  if v_contact_id is null and v_external_norm is not null then
    select c.id into v_contact_id
      from public.contacts c
      cross join lateral jsonb_array_elements(coalesce(c.phone_jsonb, '[]'::jsonb)) as phones(phone_obj)
     where public.allo_normalize_phone(phones.phone_obj ->> 'number') = v_external_norm
     order by c.id
     limit 1;
  end if;

  -- No match → auto-create a contact tagged 'lead-from-allo'.
  if v_contact_id is null then
    select id into v_lead_tag_id from public.tags where name = 'lead-from-allo' limit 1;

    insert into public.contacts (
      first_name,
      last_name,
      sales_id,
      phone_jsonb,
      tags,
      first_seen,
      last_seen,
      _sync_origin
    ) values (
      'Allo',
      coalesce(v_external_phone, 'Unknown'),
      v_sales_id,
      case
        when v_external_phone is null then '[]'::jsonb
        else jsonb_build_array(jsonb_build_object('number', v_external_phone, 'type', 'Mobile'))
      end,
      case when v_lead_tag_id is null then '{}'::bigint[] else array[v_lead_tag_id] end,
      coalesce((v_data ->> 'started_at')::timestamptz, now()),
      coalesce((v_data ->> 'ended_at')::timestamptz, (v_data ->> 'started_at')::timestamptz, now()),
      'allo'
    )
    returning id into v_contact_id;

    v_contact_created := true;
  end if;

  -- Persist the Allo↔CRM link if we have an Allo contact id and it isn't
  -- already recorded (composite PK + on conflict do nothing keeps it idempotent).
  if v_allo_contact_id is not null and v_allo_contact_id <> '' then
    insert into public.allo_contact_links (contact_id, allo_contact_id)
      values (v_contact_id, v_allo_contact_id)
      on conflict do nothing;
  end if;

  -- Attach to the contact's currently-open deal if there is exactly one
  -- candidate (archived_at IS NULL = pipeline still active). Most-recent wins
  -- on ties so the newest deal benefits from the activity log.
  select d.id into v_deal_id
    from public.deals d
   where d.archived_at is null
     and d.contact_ids @> array[v_contact_id]
   order by d.updated_at desc, d.id desc
   limit 1;

  -- Insert the call log. on conflict guards against the (very rare) race
  -- where two concurrent webhook deliveries reach this point at once.
  insert into public.call_logs (
    allo_call_id,
    direction,
    from_number,
    to_number,
    line_phone,
    status,
    duration_seconds,
    started_at,
    ended_at,
    recording_url,
    ai_summary,
    transcript,
    contact_id,
    sales_id,
    deal_id,
    raw_payload
  ) values (
    v_call_id,
    case when v_direction in ('inbound', 'outbound') then v_direction else 'inbound' end,
    v_from,
    v_to,
    v_line_phone,
    v_data ->> 'status',
    nullif(v_data ->> 'duration_seconds', '')::integer,
    nullif(v_data ->> 'started_at', '')::timestamptz,
    nullif(v_data ->> 'ended_at', '')::timestamptz,
    v_data ->> 'recording_url',
    v_data ->> 'ai_summary',
    v_data ->> 'transcript',
    v_contact_id,
    v_sales_id,
    v_deal_id,
    p_payload
  )
  on conflict (allo_call_id) do nothing
  returning id into v_inserted_id;

  v_was_inserted := v_inserted_id is not null;

  -- If the conflict path won, fetch the existing row's id so callers always
  -- see something useful in the response.
  if v_inserted_id is null then
    select id into v_inserted_id from public.call_logs where allo_call_id = v_call_id;
  end if;

  return jsonb_build_object(
    'call_log_id',     v_inserted_id,
    'contact_id',      v_contact_id,
    'sales_id',        v_sales_id,
    'deal_id',         v_deal_id,
    'inserted',        v_was_inserted,
    'contact_created', v_contact_created
  );
end;
$$;

grant all on function public.process_allo_call(jsonb) to service_role;
-- authenticated keeps it reachable from the dashboard SQL editor for ops.
grant all on function public.process_allo_call(jsonb) to authenticated;

--
-- Sanity checks (run manually after migration; commented to keep the
-- migration idempotent and side-effect free).
--
-- 1) Seed a line owner first:
--    insert into allo_line_owners(allo_phone_number, sales_id, label)
--      values ('+33744822123', 1, 'Test line') on conflict do nothing;
--
-- 2) First call → expect inserted=true, contact_created=true, lead-from-allo tag set.
--    select process_allo_call('{
--      "event": "call.completed",
--      "data": {
--        "call_id": "test-call-001",
--        "direction": "inbound",
--        "from": "+33611223344",
--        "to":   "+33744822123",
--        "line_phone": "+33744822123",
--        "started_at": "2026-05-06T10:00:00Z",
--        "ended_at":   "2026-05-06T10:02:30Z",
--        "duration_seconds": 150,
--        "status": "answered",
--        "recording_url": "https://allo.example/r/abc",
--        "ai_summary": "Demande de RDV"
--      }
--    }'::jsonb);
--
-- 3) Replay → expect inserted=false, same call_log_id (idempotency).
--    select process_allo_call('{ "data": { "call_id": "test-call-001", ... } }'::jsonb);
--
-- 4) Verify rows landed:
--    select * from call_logs where allo_call_id = 'test-call-001';
--    select id, first_name, last_name, _sync_origin, tags from contacts where _sync_origin = 'allo';
